### ISSUE TITLE
Manca WebIde

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#14]
Almeno una sezione su come abilitarlo e su a cosa serve dovremmo metterla

**Comment by EdoPut** [comment]
firstapp.md va modificato

**Comment by EdoPut** [comment]
:construction_worker: :construction_worker:  :construction_worker: lavoro titanico ma quasi compleato, adesso webide.md ha il contenuto giusto ma le immagini sbagliate, simulator.md resta com'è?

**Comment by Mte90** [comment]
vediamo il simulatore non è cambiato è cambiato solo il modo di avviarlo

**Comment by EdoPut** [comment]
Manca un'ultima immagine e poi abbiamo finito.

Ci manca uno screenshot che mostri che il telefono viene rilevato dal WebIde per fare il debug

**Comment by Mte90** [comment]
la vuoi fare te @nicokant94 ?

**Comment by nicokant94** [comment]
workin on! basta la schermata normale del WebIde con il pulsante devices premuto, giusto? tipo?
![menu_004](https://cloud.githubusercontent.com/assets/6927678/5809875/0e4a412e-a03e-11e4-9687-0863e8be824d.png)

**Comment by EdoPut** [comment]
vai ottimo, aggiungilo!

**Comment by EdoPut** [comment]
:up:
