### ISSUE TITLE
Come creare screenshot della propria applicazione

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#36]
Per presentare l'app al MarketPlace è bene avere degli screenshot decenti della propria app, magari un video

**Comment by Mte90** [comment]
per fare gli screen la responsive view li permette ma al momento il simulatore non ha questa funzionalità quindi bisognerà usare gli strumenti del sistema operativo

**Comment by EdoPut** [comment]
Mi pare che dal WebIde si possano fare, oggi vedo meglio
 Il 16/gen/2015 12:38 "Daniele Scasciafratte" <notifications@github.com> ha
scritto:

**Comment by EdoPut** [comment]
confermo che c'è l'opzione per fare screenshots del simulatore dal webIde, aggiungo al capitolo del marketplace come farli
