### ISSUE TITLE
Lista dei termini da non tradurre

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#37]
Responsive -> Responsivo, lol

**Comment by Mte90** [comment]
Si è una di quelle regole di Mozilla Italia per la traduzione...

**Comment by EdoPut** [comment]
puoi lasciare il link alla guida di Mozilla Italia per le traduzioni?

**Comment by Mte90** [comment]
https://www.dropbox.com/s/wokda3bp055m7k0/amo.txt
http://www.mozillaitalia.org/home/regole-generali-di-traduzione/

**Comment by EdoPut** [comment]
```
responsive design	-> design reattivo
responsive mode	-> modalità flessibile	è la traduzione data in Firefox
```

rimarrei sul concetto di flessibilità ed inoltre metterei una _nota del traduttore_ che indichi come parola di orginire _responsive_ visto che è la parola chiave da cercare se servono altre informazioni

**Comment by Mte90** [comment]
Ho discusso molto riguardo il termine flessibile ma i miei suggerimenti non sono passati.
Fai come ritieni più opportuno anche se da programmatore preferisco i termini in inglese.

**Comment by EdoPut** [comment]
Se posso fare come mi pare allora d'ora in poi scrivo in inglese e tanti saluti, quando verrà il momento mi mangio i revisori :grin:

**Comment by Mte90** [comment]
Bèhl a nostra guida è realizzata da volontari ma non è di mozilla quindi siamo un po' liberi riguardo come scrivere...

**Comment by EdoPut** [comment]
:+1:
