### ISSUE TITLE
riferimento a Concierge per le app hosted

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#40]
https://github.com/alexgibson/concierge è un progetto di cui vorrei tessere le lodi, è fico, è responsive, è semplice e permette di fare un bel popup discreto che ti chiede se vuoi installare il sito come WebApp, quando ho aiutato @nicokant94 a mettere su Github la sua app è stata la prima cosa che ho voluto usare

**Comment by Mte90** [comment]
non è aggiornata da tempo ma non è male la devo inserire su https://developer.mozilla.org/en-US/Apps/Reference/Firefox_OS_app_tools
Solo che non ha il supporto di riconoscimento dei browser che ha la soluzione che ho realizzato io ma potrei sempre fare un fork

**Comment by EdoPut** [comment]
puoi lasciarmi il link al tuo lavoro?

**Comment by Mte90** [comment]
trovi i link nella pagian che ho linkato che contiene i miei snippet

**Comment by EdoPut** [comment]
ok trovato, è importante il riconoscimento del browser? posso segnalare queste restrizioni nel manifest?

**Comment by Mte90** [comment]
Se vuoi che l'app sia installabile solo su Firefox for android o firefox desktop il riconoscimento è utile

**Comment by EdoPut** [comment]
Il manifest è personalizzabile vero? Basta che passi la validazione e poi
tutto a posto, nel caso suggerisco di aggiungere il campo
supported/avaiable e mettere un array con i sistemi disponibili, in questo
modo basta un codice del genere:

If sistema in package.avaiable
  Prompt install
Else
  Don't prompt
 Il 11/gen/2015 15:58 "Daniele Scasciafratte" <notifications@github.com> ha
scritto:

**Comment by Mte90** [comment]
Non ti sò dire se il manifest è personalizzabile e si possono inserire parametri non standard

**Comment by EdoPut** [comment]
https://github.com/mozilla/app-validator, adesso sono un po' corto col tempo ma sarebbe il momento di cominciare

**Comment by Mte90** [comment]
basta provare a caricarne uno su https://marketplace.firefox.com/developers/validator
Però credo che sia sbagliato proporre queste cose nel manifest in una guida introduttiva

**Comment by EdoPut** [comment]
`Però credo che sia sbagliato proporre queste cose nel manifest in una guida introduttiva` concordo ma in questo momento il progetto è un'altro, aggiungere funzioni a Concierge, poi possiamo benissimo non parlarne nella guida e lasciare un link alla versione attuale senza citare la nostra fork

**Comment by Mte90** [comment]
Ahhhh bèh se parliamo di concierge la questione è un'altra certo.
al momento tralscia la questione del fork nelal guida che è fuorviante

**Comment by EdoPut** [comment]
Inserisco in other.md
