### ISSUE TITLE
LeanPub

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#41]
Quel "versione live non pronta" deve morire, come possiamo fare?

**Comment by Mte90** [comment]
con versione live mi riferisco alla versione caricata su leanpub, posso farla anche se la guida non è ancora pronta ma diciamo almeno quasi finita.

**Comment by nicokant94** [comment]
per una versione live vera e propria si potrebbe caricare il libro su www.gitbook.com

**Comment by Mte90** [comment]
Il libro usa un mix di sintassi di markdown e latex perchè leanpub ha un suo generatore specifico che non è possibile trovare scaricaribile.
Per questo uso uno script che compila il markdown e latex in pdf.
In poche parole possiamo caricarlo solo su leanpub :-/
Ho aggiornato il link nelal descrizione del repo per scaricare il pdf compilato aggiornato.
Se volete posso caricare l'ebook su leanpub scrivendo che è in beta tanto ho visto che in diversi caricano lì i libri i nscrittura anche perchè a chi li ha scaricati gli arriva un'email per inormare di un'eventuale aggiornamento.

**Comment by EdoPut** [comment]
Leanpub usa [markua](http://markua.org/) per fare la conversione

**Comment by Mte90** [comment]
peccato che non sia scaricabile un compilatore -.-'

**Comment by EdoPut** [comment]
fortunatamente LeanPub usa i webhook (da quanto ho capito) quindi potremmo configurarne uno per ogni nuova release e darci una tabella di release bimestrali fino a che non è pronta la versione definitiva

**Comment by Mte90** [comment]
mi occupo io di studiarmi questa cosa allora :-)

**Comment by Mte90** [comment]
se vogliamo il sync automatico che ho predisposto dobbiamo spostare tutti i file in una cartella `manuscript`. La pagina sarà questa https://leanpub.com/guidavelocesviluppofirefoxos una volta che sarà caricata, oltre alla img che mi manderanno.

**Comment by EdoPut** [comment]
Adesso è tutto configurato, manca solo la copertina in Italiano, per cui apro un nuovo Issue, il #47

**Comment by Mte90** [comment]
registratevi su leanpub così vi metto tra i contributori e datemi il vostro nick

**Comment by EdoPut** [comment]
EdoPut come dappertutto

**Comment by Mte90** [comment]
Bisogna capire come fargli prendere l'immagine a leanpub
