### ISSUE TITLE
Copertina in Italiano

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#47]

**Comment by soapdog** [comment]
Working on it!

**Comment by soapdog** [comment]
Please paste the correct Italian phrase for the cover

**Comment by EdoPut** [comment]
It's __"Guida veloce allo sviluppo per Firefox OS"__, thank you!

**Comment by Mte90** [comment]
Che spettacolo!
![firefox_os_it_1](https://cloud.githubusercontent.com/assets/403283/6063202/b490048c-ad55-11e4-9f3f-0261395aa949.png)

**Comment by EdoPut** [comment]
:+1:
