### ISSUE TITLE
LeanPub preview fallita

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#50]
Il servizio di Preview fallisce perché il file __Book.txt__ risulta vuoto

**Comment by EdoPut** [comment]
[https://groups.google.com/forum/#!topic/leanpub/moXPqdtoeQo](https://groups.google.com/forum/#!topic/leanpub/moXPqdtoeQo) potrebbe essere un problema di WebHooks

**Comment by Mte90** [comment]
Si ho visto ho contattato l'assistenza

**Comment by EdoPut** [comment]
Lascio nelle tue mani allora
Il 06/feb/2015 10:25 "Daniele Scasciafratte" <notifications@github.com> ha
scritto:

**Comment by EdoPut** [comment]
:up:

**Comment by Mte90** [comment]
Se ti dico che mi hanno risposto il 6 ma non mi è arrivata nessuna notifica?
https://groups.google.com/forum/#!topic/leanpub/ZNf8iphDIxY
Dicono che il problema è il ramo.
O mergiamo la 0.3 con master o rinominiamo master in old (lo mantengo perchè è una traduzione completa della versione originale senza aggiunte, oramai non è aggiornata) e 0.3 diventa master.

**Comment by EdoPut** [comment]
approvato! me ne occupo subito
