### ISSUE TITLE
Landing page spoglia

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#56]
https://leanpub.com/guidavelocesviluppofirefoxos è praticamente vuota

**Comment by Mte90** [comment]
Adesso che funziona la miglioro :-)

**Comment by EdoPut** [comment]
#58

**Comment by Mte90** [comment]
Aggiunto il testo riguardo gli autori

**Comment by Mte90** [comment]
Direi che adesso non è male

**Comment by EdoPut** [comment]
:smile:
