### ISSUE TITLE
Elenco delle differenze 

### ISSUE THREAD

**Issue by Mte90** [Mte90/firefoxos-quick-guide#58]
Elenco delle differenze tra la versione originale e la nostra.
In poche parole l'elenco del materiale nuovo.

**Comment by Mte90** [comment]
* Linee guida marketplace
* Informazioni sul manifest
* Capitolo sul Boilerplate e su l10n.js
* Elenco webActivity
* Web Component, Moz Polyfill, Firefox Developer edition citati
* Github pages

@EdoPut manca qualcosa?

**Comment by EdoPut** [comment]
Stasera ci do un occhio, promesso

**Comment by EdoPut** [comment]
* più di venti nuove pagine di materiale
* i nuovi strumenti per gli sviluppatori
* usare un telefono Firefox OS per il debug (?)
* materiale revisionato e aggiornato al 2015

**Comment by Mte90** [comment]
*     Linee guida per il marketplace dove potrai pubblicare la tua app
*     Informazioni sul manifest che è la carta d'identità della tua app
*     Capitolo sul Boilerplate e su l10n.js che ti permetteranno di lavorare meglio
*     Elenco delle webActivity per capire subito le potenzialità del sistema
*     Web Component, Moz Polyfill, Firefox Developer edition sono alcune delle tecnologie spiegate
*     Come sfruttare le Github pages per la tua app
*     I nuovi strumenti per gli sviluppatori come il WebIDE
*     Usa un telefono Firefox OS per il debug con Firefox
*     Il materiale è revisionato e aggiornato al 2015

L'ho trasformato così e messo nella landing

**Comment by EdoPut** [comment]
Bene, ottimo.
