### ISSUE TITLE
meta description

### ISSUE THREAD

**Issue by EdoPut** [Mte90/firefoxos-quick-guide#60]
160 caratteri che verrano indicizzati dai motori di ricerca:

ecco la mia proposta:

```
Una guida per tuffarsi nello sviluppo di applicazioni per Firefox OS
```

molto banale

**Comment by Mte90** [comment]
Non trovo la sezione nella configurazione per inserirla

**Comment by EdoPut** [comment]
[Landing Page](https://leanpub.com/guidavelocesviluppofirefoxos/edit_landing_page)
