### ISSUE TITLE
Togliere immagini appmanager

### ISSUE THREAD

**Issue by Mte90** [Mte90/firefoxos-quick-guide#62]
La sezione è stata tolta ma il repo contiene ancora quelle immagini.
Si possono togliere o sono usate altrove?

**Comment by EdoPut** [comment]
ok, questo è un nuovo test da aggiungere

**Comment by EdoPut** [comment]
Dal test non risulta che le immagini siano state usate nella nuova versione

**Comment by Mte90** [comment]
direi che possiamo rimuoverle

**Comment by EdoPut** [comment]
integrati i cambiamenti in master
